### ISSUE TITLE
Add Deno support

### ISSUE THREAD

**Issue by PylotLight** [gowebly/gowebly#107]
**Required check list:**

- [X] I didn't find in the repository's issues section a similar bug.
- [X] I understand, this is an Open Source and not-for-profit product.
- [ ] This is not about a third-party project, framework, or technology.

**Is your feature request related to a problem? Please describe.**

N/A

**Describe the solution you'd like:**

It would be good to add Deno 2.0 support now that it's fully released, as an alternative option to bun.

**Describe alternatives you've considered:**

Bun is good, but having another option is always better :p

**Screenshots:**

N/A

**Additional context:**

N/A

**Comment by koddr** [comment]
Hi, @PylotLight

Yep. Adding Deno support to Gowebly is on my backlog now. Coming soon 👍

**Comment by koddr** [comment]
@PylotLight unfortunately, Deno 2.x also does not support normal operation with key packages (Parcel, Prettier, and so on). 

Until this support is enabled, it is not possible to add Deno to the Gowebly CLI.

**Comment by PylotLight** [comment]
> @PylotLight unfortunately, Deno 2.x also does not support normal operation with key packages (Parcel, Prettier, and so on).
> 
> Until this support is enabled, it is not possible to add Deno to the Gowebly CLI.

Doesn't Deno provide it's own version of these 2 tools, thus you wouldn't want to use them anyway?
Can you expand why this is a limitation?
