### ISSUE TITLE
Doesn't create the file ".gowebly.yml"  when running the command line: `gowebly init`

### ISSUE THREAD

**Issue by wizenith** [gowebly/gowebly#15]
**Required check list:**

- [x] I didn't find in the repository's issues section a similar bug.
- [x] I understand, this is an Open Source and not-for-profit product.
- [x] This is not about a third-party project, framework, or technology.

**My environment:**
WSL2/Linux (Ubuntu 22.04.3 LTS)
gowebly version 1.3.2
go version go1.21.1 linux/amd64
node v20.5.1
...

**Describe the bug:**
When running the command `gowebly init`, it shows this error:
```
❯ gowebly init
                          _     _
   __ _  _____      _____| |__ | |_   _
  / _` |/ _ \ \ /\ / / _ \ '_ \| | | | |
 | (_| | (_) \ V  V /  __/ |_) | | |_| |
  \__, |\___/ \_/\_/ \___|_.__/|_|\__, |
  |___/ build amazing Go web apps |___/

○ Generating a default config file... Please wait!

✕ Please fix error(s):

 – open configs/default.yml: file does not exist

‼ To print all commands, just run 'gowebly' without any commands or options
‼ For more information, see https://gowebly.org
```

**Comment by koddr** [comment]
Hi @wizenith 

Nice catch! Thanks 👍

Fixed in `v1.3.3` version.
