### ISSUE TITLE
Gen web manifest

### ISSUE THREAD

**Issue by gedw99** [gowebly/gowebly#17]
https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable

all browsers on all desktops and mobiles finally support the A2HS feature so that users can installl a web app via the web or also app stores ..

This is grunt work that devs should not have to do so I think it’s a good thing to add to a htmx app.

the link links to a PWA builder and publisher . It apparently can gen the code to publish to an App Store too .

**Comment by koddr** [comment]
Hi @gedw99 

Thanks for feature request! I'll add that in the next version (`v1.4.0`).

**Comment by koddr** [comment]
Added in `v1.4.0`. Please update CLI 😉
