### ISSUE TITLE
Error invalid cross-device link when run gowebly create 

### ISSUE THREAD

**Issue by afasari** [gowebly/gowebly#2]
**Required check list:**

- [x] I didn't find in the repository's issues section a similar bug.
- [x] I understand, this is an Open Source and not-for-profit product.
- [x] This is not about a third-party project, framework, or technology.

**My environment:**

- OS Windows 11 with WSL 2 Ubuntu 22.04:
- Go 1.21.1 linux/amd64):
- gowebly 1.0.0:

**Describe the bug:**

After I run 
```
go run github.com/gowebly/gowebly@latest create
```
the result is rename /tmp/1160007634 go.mod: invalid cross-device link
...

**Steps to reproduce the behavior:**

1. install gowebly
2. init gowebly
3. create gowebly

**Expected behavior:**

all boilerplate file must be created

**Screenshots:**

![image](https://github.com/gowebly/gowebly/assets/24645546/29fa9105-d158-4b50-b908-e7dfe98b94fe)

**Additional context:**

Is it issue about using WSL 2 Ubuntu 22.04? Is there any chance to run it via Windows 11?

**Comment by koddr** [comment]
Hi @afasari,

Thanks so much for highlighting this problem, as my native system is GNU/Linux and macOS. 

> I haven't had much time to test on Windows 10/11. The tests I did via virtual machines did not reveal this issue (unfortunately).

As far as I have been able to research the situation with Windows 11 and WSL 2, the `go.mod cross-device link` error usually occurs when the Go module files are on different file systems or different devices. In case you are using WSL 2, you may have issues with file synchronization between Windows and Ubuntu.

I can recommend the following:

1. Make sure that your project and Go module are on the same file system that does not cross different devices. For example, if your project is on the `C:\` drive, make sure the Go module is also on the `C:\` drive.
2. Check the file synchronization settings in WSL 2. Make sure that the directories containing your project and Go module are properly configured for synchronization between Windows and Ubuntu.
3. Rebuild the Go module. Delete the `go.mod` file, `go.sum` and the `./vendor` folder (if any), and then run the `go mod tidy` command to rebuild the dependencies.
4. Try using a different version of WSL or Ubuntu. Sometimes file synchronization issues may be related to a particular version of WSL or Ubuntu.

Hope this help 😉

**Comment by afasari** [comment]
Hello @koddr, thank you for your response

I already explored the bug and find out that there is a solution with this [PR](https://github.com/gowebly/gowebly/pull/3)
Also, I found another bug that was also fixed on that PR. I already tested it and works fine. 
If may, please review my PR. I just found this repo and I think this repo is best for my simple personal projects. Hopefully, this repo can used by more people

**Comment by dubrsl** [comment]
Got the same error with tag 1.1.0 :(

**Comment by koddr** [comment]
Hi @dubrsl 

Yeah, we're already working it out with @afasari. I have poured a possible solution into his PR.

Please try this commit on your machine: [eaedc1e](https://github.com/gowebly/gowebly/pull/3/commits/eaedc1e63dfcd4452af9bcbcfcfeb79d667f5c50)

**Comment by koddr** [comment]
Fixed in `v1.2.0` 🎉
