### ISSUE TITLE
Create action : manifest-desktop-screenshot.jpeg: file does not exist

### ISSUE THREAD

**Issue by mwolff44** [gowebly/gowebly#20]
**Required check list:**

- [x] I didn't find in the repository's issues section a similar bug.
- [x] I understand, this is an Open Source and not-for-profit product.
- [x] This is not about a third-party project, framework, or technology.

**My environment:**

✓ gowebly version 1.4.0
 ✓ go version go1.21.1 linux/amd64
 ✓ docker version 24.0.6, build ed223bc

...

**Describe the bug:**

```sh
$ gowebly create
                          _     _       
   __ _  _____      _____| |__ | |_   _ 
  / _` |/ _ \ \ /\ / / _ \ '_ \| | | | |
 | (_| | (_) \ V  V /  __/ |_) | | |_| |
  \__, |\___/ \_/\_/ \___|_.__/|_|\__, |
  |___/ build amazing Go web apps |___/ 
                                            
○ Preparing the backend part... Please wait!
○ Downloading and preparing the frontend part... Please wait!
                      
✕ Please fix error(s):
                      
 – open static/manifest-desktop-screenshot.jpeg: file does not exist
```

...

**Comment by koddr** [comment]
Thanks, @mwolff44 

Fixed in `v1.4.1` 🎉
