### ISSUE TITLE
Error with last version of bun

### ISSUE THREAD

**Issue by iezed** [gowebly/gowebly#27]
Hi,
I have this bug :
https://github.com/oven-sh/bun/issues/6869
would it be possible to downgrade to version 1.0.7 of bun?

**Comment by koddr** [comment]
Hi, @iezed 

I don't really understand how this bug in Bun relates to the Gowebly CLI project? 

This CLI does not install Bun for you, but only uses the already installed version on your system. Therefore, you can make a downgrade on your own right now.

**Comment by iezed** [comment]
Hi, you're right.

**Comment by iezed** [comment]
Hi, you're right.
