### ISSUE TITLE
Request info

### ISSUE THREAD

**Issue by iezed** [gowebly/gowebly#30]
Hi, thank you for your project.
I'd like to ask you some information:
1) how do you see the version of htmx? Can I upgrade it to the latest version?
2) which framework and template combination is most suitable for small projects?
Thank you.

**Comment by koddr** [comment]
Hi, @iezed 

I'll answer in the same order:

1. The latest version of **htmx** and **hyperscript** is downloaded automatically (during `create`, `run` and `build` commands) if `htmx: latest` and `hyperscript: latest` parameters are set in `.gowebly.yml` file respectively. You can set any version to your liking.
2. In my opinion, the best for small projects would be a bundle of **Fiber** backend and **Tailwind CSS** frontend. It's the perfect way to start when you don't know these technologies yet.

**Comment by iezed** [comment]
Hi, @koddr

Being in a learning phase, it would be useful to have a way to recreate the project, without deleting everything. It's possible? gowebly create ask for empty folder.
How do I change BACKEND_PORT? 
I tried to put BACKEND_PORT=5000 in .env, but it doesn't work.
If I add a new post or get method, the favicon.ico file is not found. Wouldn't it be better to move favicon.ico to the root of static?
Thanks.

**Comment by koddr** [comment]
To change the port, you can change the `port` option in the `.gowebly.yml` file. You don't need to recreate anything! 

> That's the good thing about the Gowebly CLI, because it helps you quickly change this configuration of your application.

The answers to the other questions are better found in the documentation for environment variables and how the `.env` file works, as they are more fundamental and require a base.

**Comment by koddr** [comment]
@iezed by the way, we launched the official Gowebly CLI docs: https://gowebly.org/

Hope you find answers to all of your questions! 😊
