### ISSUE TITLE
Can't select UnoCSS

### ISSUE THREAD

**Issue by devpikachu** [gowebly/gowebly#47]
**Required check list:**

- [x] I didn't find in the repository's issues section a similar bug.
- [x] I understand, this is an Open Source and not-for-profit product.
- [x] This is not about a third-party project, framework, or technology.

**My environment:**

```    
│ Gowebly CLI: v2.1.1 (build with go1.21.6 on linux/amd64) 
│                                                          
│ Go: 1.21.6 linux/amd64                                   
│ Node.js version: 20.11.0 (npm 10.3.0)                    
│ Bun version: 1.0.25                                      
│                                                          
│ Is Air tool installed? false                             
│ Is Templ package installed? true
```

**Describe the bug:**

In the `gowebly create` process, I can't select UnoCSS as a styling library.

**Steps to reproduce the behavior:**

1. Run `gowebly create` until the styling library selection step

**Expected behavior:**

UnoCSS should be selectable.

**Screenshots:**

N/A

**Additional context:**

N/A

**Comment by koddr** [comment]
Hi, @devpikachu 

Nice catch, thank you!

Fixed in `v2.1.2` release.
