### ISSUE TITLE
Check for Project Dependencies before applying any changes.

### ISSUE THREAD

**Issue by jakeecolution** [gowebly/gowebly#50]
**Required check list:**

- [X] I didn't find in the repository's issues section a similar bug.
- [X] I understand, this is an Open Source and not-for-profit product.
- [X] This is not about a third-party project, framework, or technology.

**Is your feature request related to a problem? Please describe.**

It would be nice if the program would check for programatic dependencies of binaries before generating files or have a clean up feature to undo all committed files so new users don't have to remove all files first.

...

**Describe the solution you'd like:**

Preferred solution is to check upon start for 3rd party dependencies such as `templ`, `bun`, etc. I don't think this would take too much effort. I'll look at creating a PR for making this solution to go through each third-party dependency and identify whether it is in the path, give a link to the installation instructions of the binaries, and if they want to continue without those dependencies it might be a good solution for a super user who doesn't want to use those third party dependencies.

...

**Describe alternatives you've considered:**

If you keep a running list of files you've added, then delete them if you run into a third-party dependency. Also, another idea I have is to create a folder named after the project name and place all generated files into that directory so if something like this does come up, then it is really easy to delete the files and fix the user errors.

...

**Screenshots:**

![image](https://github.com/gowebly/gowebly/assets/5884696/ef5f499c-70c5-4043-9957-e3a7acd05cb4)
![image](https://github.com/gowebly/gowebly/assets/5884696/40cccbb7-60eb-4935-9573-8c4f1c743138)

...

**Additional context:**

I don't see this as a big feature need but it would definitely make the developer experience much better. Thanks and I look forward to getting some input from you.

...

**Comment by jakeecolution** [comment]
@koddr - Let me know what you think about best steps forward and I can work on a solution. Thanks!

**Comment by koddr** [comment]
Hi, @jakeecolution 

Thank you for your interest in this project.

To check the current configuration in the Gowebly CLI, there is a [`doctor`](https://gowebly.org/complete-user-guide/info-about-system#info-about-your-system) command that can help identify packages that are installed on the system and will be used by the CLI:

```console
$ gowebly doctor

✓ Your system information has been collected successfully!
                                                          
│                                                           
│ Copy this information to paste into an issue ↘            
│                                                           
│ Gowebly CLI: v2.2.0 (build with go1.22.0 on darwin/arm64) 
│                                                           
│ Go: 1.22.0 darwin/arm64                                   
│ Node.js version: 21.6.1 (npm 10.2.4)                      
│ Bun version: 1.0.26                                       
│                                                           
│ Is Air tool installed? true                               
│ Is Templ package installed? true                          
│                                                           
                                                                    
✱ For more information go to the official docs: https://gowebly.org 
```

But, I'm ready to accept any help to improve this product! 😉

**Comment by koddr** [comment]
@jakeecolution I'll close this issue so that it doesn't get in the way.

If it still exists, please re-open it or start a [discussion](https://github.com/gowebly/gowebly/discussions).
