### ISSUE TITLE
install project dependencies

### ISSUE THREAD

**Issue by ricklyman** [gowebly/gowebly#53]
**Required check list:**

- [x] I didn't find in the repository's issues section a similar bug.
- [x] I understand, this is an Open Source and not-for-profit product.
- [x] This is not about a third-party project, framework, or technology.

**My environment:**

Benefits of the go run command

With go run, you can use all features of the Gowebly CLI without installation to your system.
...

**Describe the bug:**

action:
 go run github.com/gowebly/gowebly/v2@latest create
...
result:
failed to run action 'install project dependencies' in goroutine: can't execute command 'templ' with option '[generate]': exec: "templ": executable file not found in $PATH 

**Steps to reproduce the behavior:**

1. ...action above (go run github.com/gowebly/gowebly/v2@latest create)
2. ...
3. ...

**Expected behavior:**

definition of executable file not found
.gowebly executable?
 ..
?With go run, you can use all features of the Gowebly CLI without installation to your system.

**Screenshots:**

...

**Additional context:**

...

**Comment by koddr** [comment]
Hi, @ricklyman 

Please send me the output of the `gowebly doctor` command.

**Comment by ricklyman** [comment]
$ gowebly doctor

✓ Your system information has been collected successfully!
                                                          
│                                                          
│ Copy this information to paste into an issue ↘           
│                                                          
│ Gowebly CLI: v2.3.0 (build with go1.22.0 on linux/amd64) 
│                                                          
│ Go: 1.22.0 linux/amd64                                   
│ Node.js version: not installed (npm not installed)       
│ Bun version: not installed                               
│                                                          
│ Is Air tool installed? false                             
│ Is Templ package installed? false                        

hmmm...
https://gowebly.org/getting-started/quick-start-guide
First, [download](https://go.dev/dl/) and install Go. Version 1.21 (or higher) is required.
Second, install Bun or Node.js ?

**Comment by koddr** [comment]
Yeah, I see what you're talking about.

Logically, the Gowebly CLI creates a full-cycle starter web application. That is, you have to have Node.js (or Bun) installed on your PC by default, otherwise how would you develop the frontend part? 🤔

So to be honest, I couldn't think that someone might not have this installed.

OK, I'll add a note about this to the documentation in upcoming versions, so there's no ambiguity in reading the recommendations.

**Comment by koddr** [comment]
@ricklyman updated section "[Quick start guide](https://gowebly.org/getting-started/quick-start-guide#quick-start-guide)" in docs with:

> [...] You can check which of the recommended tools are already installed on your system by using the doctor utility built into the Gowebly CLI:
>
> `go run github.com/gowebly/gowebly/v2@latest doctor`
>
> If some tools are not installed, it is recommended that you install them yourself. Especially Node.js (or Bun) for building frontend parts of your application. [...]
