### ISSUE TITLE
Windows compatibility with use of Air

### ISSUE THREAD

**Issue by eddyvy** [gowebly/gowebly#54]
**Required check list:**

- [X] I didn't find in the repository's issues section a similar bug.
- [X] I understand, this is an Open Source and not-for-profit product.
- [X] This is not about a third-party project, framework, or technology.

**Is your feature request related to a problem? Please describe.**

The binary created for developing in Windows is not working.

**Describe the solution you'd like:**

The command "create" should create a project compatible with Windows.

**Describe alternatives you've considered:**

Add the ".exe" extension to the air.toml to make it work.

**Screenshots:**

N/A

**Additional context:**

Using these tools in a Windows / Powershell environment

**Comment by koddr** [comment]
Fixed in #56 

Please update CLI to `v2.3.1` and test this on your Windows PC 😉

**Comment by eddyvy** [comment]
> Fixed in #56
> 
> Please update CLI to `v2.3.1` and test this on your Windows PC 😉

Now works perfect!
