### ISSUE TITLE
When developing, the cache of the browser does not invalidate style.css and stale data is returned

### ISSUE THREAD

**Issue by superjose** [gowebly/gowebly#60]
**Required check list:**

- [x] I didn't find in the repository's issues section a similar bug.
- [x] I understand, this is an Open Source and not-for-profit product.
- [x] This is not about a third-party project, framework, or technology.

**Is your feature request related to a problem? Please describe.**

First of all, @koddr, thank you so much for all the time and effort you've put into creating this nifty CLI!

The time and effort are incredibly appreciated! 

I'm starting with Go and building my first serious project with this CLI. 

I'd love to hear back from you regarding my approach. My background is in TypeScript, React, C#, and Node. While I try to do my best, my mindset bleeds into Go. 

Please take these with a grain of salt, as I don't know if these are the best approaches!!!

Problems / Solutions:
1.	I didn’t know the main styles overriding the application. I finally found that they came from `styles.css`. The documentation should say that the global styles.css is generated from a `styles.scss` file, or the styles should be contained within the main.templ file.

2.	The browser automatically caches the style.css from `main.templ`. I’ve come to pass an environment variable to templ to generate a simple random string to append it to the style.css in main.templ to invalidate the cache. I have no idea if this is the best way to do it, nor if this is how the package bundlers do it. But it works!

```
if props.IsDevelopment {
                <link href={ fmt.Sprintf("/static/styles.css?regen=%d", rand.IntN(1000)) } rel="stylesheet"/>
            } else {
                <link href="/static/styles.css" rel="stylesheet"/>
            }
}
```

3.	It’d be awesome if there could be a way to hot module reload whenever the UI changes.

**Comment by koddr** [comment]
Hi, @superjose 

Thank you for the kind words addressed to Gowebly CLI. This makes me work harder on the project every day to create an even better solution!

Regarding your questions, I will answer in the same order:

1. Yes, it was specified earlier (in `v1`). I will add this to the documentation soon.

2. Yes, you can use this approach. Why not, right? :wink: Usually, I always disable the browser cache at the time of debugging or developing web applications (on my local PC) whose styles/scripts can be cached by the browser.

3. In fact, the hot reboot has already been implemented, thanks to the Air tool (it monitors changes in files, bundles CSS/JS and restarts the Go application). You can enable its generation when creating a new project via the Gowebly CLI.

**Comment by koddr** [comment]
I rolled out updates for the documentation section "[Create a new project](https://gowebly.org/complete-user-guide/create-new-project)". 
I specified a description for folders and files in the project being created.

Please see if everything is clear now? 🙌

**Comment by superjose** [comment]
@koddr Oh that's awesome 🤗 

Sorry for taking so long to reply!

Thank you very much for the feedback. Using gowebly and looking good so far!
