### ISSUE TITLE
Node-free Tailwind/UnoCSS

### ISSUE THREAD

**Issue by jthegedus** [gowebly/gowebly#65]
**Required check list:**

- [x] I didn't find in the repository's issues section a similar bug.
- [x] I understand, this is an Open Source and not-for-profit product.
- [ ] This is not about a third-party project, framework, or technology.

**Is your feature request related to a problem? Please describe.**

I don't want the Node toolchain.

**Describe the solution you'd like:**

Tailwind v4 looks to remove the need for PostCSS & co. Once v4 has it's standalone CLI released, it would be great to see a version of GoWebly that has Node-free Tailwind support. Even more ideal would be the same for UnoCSS.

**Describe alternatives you've considered:**

I currently don't use GoWebly because of the requirement of Node for Tailwind/UnoCSS.

**Screenshots:**

...

**Additional context:**

https://tailwindcss.com/blog/tailwindcss-v4-alpha

**Comment by koddr** [comment]
Hi, @jthegedus 

Yes, I also fully support the concept of switching to Bun from Node.js. 
I've been using it in my projects for a long time, even before version 1.0.0. 

As soon as the stable release of Tailwind CSC 4.0.0 is available, I will add the option to select the Node-free installation option for the Gowebly CLI.

**Comment by jthegedus** [comment]
>switching to Bun from Node.js

I don't mean to suggest making Bun the default, ideally there would be no JS runtimes at all, just a pure Go project. I am not sure how to orchestrate installing the Tailwind v4 CLI, but ideally that would be something done outside the JS ecosystem, with either no external dependency or somehow within the Go ecosystem.

**Comment by koddr** [comment]
I don't really understand the desire to move what JS does well in the browser inside the backend. What for? What advantages will this have for a particular developer? 

Please describe examples of using this approach in modern web development. Otherwise, I just don't understand the purpose of this feature.

**Comment by jthegedus** [comment]
Currently using the Tailwind styling option will require Node.js or Bun for installing PostCSS and Tailwind.

After Tailwind 4.0, since Tailwind itself will do all the PostCSS stuff, I shouldn't really need Node.js or Bun, simply to install the Tailwind standalone CLI, this tool could do that instead of relying on Node/Bun + package.json.

**Comment by jthegedus** [comment]
@koddr The 4 beta has released https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.0-beta.1

**Comment by koddr** [comment]
> @koddr The 4 beta has released https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.0.0-beta.1

Yes, waiting for stable release.

**Comment by jthegedus** [comment]
Please see - https://github.com/hookenz/gotailwind
