### ISSUE TITLE
Add Flowbite to CSS frameworks

### ISSUE THREAD

**Issue by zoltanszogyenyi** [gowebly/gowebly#68]
I think it would be really cool to also add Flowbite to the supported CSS frameworks.

It's quite popular with over 10 million downloads on NPM and has a large open-source collection of UI components:

https://github.com/themesberg/flowbite

Cheers <3

**Comment by koddr** [comment]
Hi, @zoltanszogyenyi 

The Flowbite has already been added to the Gowebly CLI (starting with version [v1.10.0](https://github.com/gowebly/gowebly/releases/tag/v1.10.0)).
