### ISSUE TITLE
Project not created  and getting OOPs with different message in different try

### ISSUE THREAD

**Issue by Hakuz** [gowebly/gowebly#71]
**Required check list:**

- [ x] I didn't find in the repository's issues section a similar bug.
- [ x] I understand, this is an Open Source and not-for-profit product.
- [ x] This is not about a third-party project, framework, or technology.

**My environment:**

Gowebly CLI: v2.5.0 (build with go1.22.2 on darwin/arm64) 
│                                                           
│ Go: 1.22.2 darwin/arm64                                   
│ Node.js version: not installed (npm not installed)        
│ Bun version: 1.1.7                                        
│                                                           
│ Is Air tool installed? true                               
│ Is Templ package installed? true       
...

**Describe the bug:**

Getting Oops message while trying to create the project...

✕ Oops... Something went wrong!
                             
│                                                                                                                                        
│ failed to run action 'install project dependencies' in goroutine: can't execute command 'bun' with option '[run build]': exit status 1 

In the next retry got different message
✕ Oops... Something went wrong!                          
│                                                                                                                                   
│ failed to run action 'generate backend files' in goroutine: file '.dockerignore' is exists, can't be overwritten (clean up first) 

**Steps to reproduce the behavior:**

1. Use Air tool : Yes
2. Use Bun as framework : Yes
3. Use Templ package : Yes
4. use Golang CI lint : Yes
5. Select the go framework or router : Echo
6. select the reactivity library : htmx
7. Select the CSS library : Tailwind CSS with Preline UI components 
8. What's your go module name : testgw
9. project name in package json : gowebtest
10. port for backend server : 7000                                                                                                                                                               

**Expected behavior:**

A working project with selected dependencies
...

**Screenshots:**

...

**Additional context:**

...

**Comment by koddr** [comment]
Hi, @Hakuz 

This is because Parcel bundler gets error when running `bun install`, like this:

```console
TypeError: m.load is not a function. (In 'm.load(filePath)', 'm.load' is undefined)
      at load (/Users/user/project/node_modules/@parcel/package-manager/lib/index.js:3624:13)

10 |   }
11 | }
12 |
13 | let binding;
14 | try {
15 |   binding = require(name);
     ^
TypeError: symbol 'napi\_register\_module\_v1' not found in native module. Is this a Node API (napi) module?
      at dlopen (native:1:1)
      at /Users/user/project/node_modules/@parcel/watcher/index.js:15:2
      at anonymous (native:1:1)
      at /Users/user/project/node_modules/@parcel/fs/lib/index.js:21:5
      at anonymous (native:1:1)
      at /Users/user/project/node_modules/@parcel/package-manager/lib/index.js:35:5
      at anonymous (native:1:1)
      at /Users/user/project/node_modules/@parcel/core/lib/worker.js:102:1
      at anonymous (native:1:1)
      at /Users/user/project/node_modules/@parcel/workers/lib/child.js:111:19
10 |   }
11 | }
12 |
13 | let binding;
14 | try {
15 |   binding = require(name);
     ^
```

I'll figure it out, but I'd appreciate some help in fixing the Parcel failure.

**Comment by koddr** [comment]
BTW, I create bug report in Parcel repo: https://github.com/parcel-bundler/parcel/issues/9707

**Comment by Hakuz** [comment]
For now i uninstalled the bun and installed the nodejs and it started to work. Will switch to bun once the Parcel fixes the issues. Thanks for your quick help.
