### ISSUE TITLE
Preline UI does not include standard TailwindCSS imports

### ISSUE THREAD

**Issue by pdf** [gowebly/gowebly#73]
**Required check list:**

- [x] I didn't find in the repository's issues section a similar bug.
- [x] I understand, this is an Open Source and not-for-profit product.
- [x] This is not about a third-party project, framework, or technology.

**My environment:**

│ Gowebly CLI: v2.5.0 (build with go1.22.3 on linux/amd64) 
│                                                          
│ Go: 1.22.3 linux/amd64                                   
│ Node.js version: 18.18.2 (npm 10.7.0)                    
│ Bun version: 1.1.8                                       
│                                                          
│ Is Air tool installed? true                              
│ Is Templ package installed? true
...

**Describe the bug:**

When generating a project using Preline UI the standard TailwindCSS imports are missing, ie:

`assets/styles.scss`
```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

This results in the Tailwind classes being unavailable.

...

**Steps to reproduce the behavior:**

1. Create project, enabling `Tailwind CSS with Preline UI components`.
2. Review generated SCSS.
3. Run build and note that TailwindCSS classes are unavailable.

**Expected behavior:**

As when generating for base `Tailwind CSS`, the Tailwind imports should be included in the generated `assets/styles.scss`.

...

**Screenshots:**

...

**Additional context:**

Looks like probably just a missing condition here?

https://github.com/gowebly/gowebly/blob/fbab5cf49b452e2d6bd7fa2118e6868b83b26139/internal/attachments/templates/frontend/styles.scss.gotmpl#L1
...

**Comment by koddr** [comment]
Hi, @pdf 

Nice catch, thanks!
