### ISSUE TITLE
Bug: Naming projects and editing with textcursor causes space in the middle of the name

### ISSUE THREAD

**Issue by lmbek** [gowebly/gowebly#80]
**BUG: When creating a project and naming the project. You cannot leave the textcursor in the middle of the text**

Hello, when i was trying to use gowebly, i noticed a bug.

**What happened**
I was creating a new project with: 
`go run github.com/gowebly/gowebly/v2@latest create`

Then when i had to name the project, i named it trying_gowebly

I noticed if i used the arrow keys to go left in the text, then where the textcursor was, it would add a space after the textcursor.
So the name would be trying_ gowebly or tryinggow ebly

Example:
MyProje|ctName

textcursor at MyProje 
and then it will add a space before continuing with ctName

This causes a problem for go mod tidy right after.

**What did i expect**
I expected the name to not have a space added to it, where i left the textcursor

**Comment by lmbek** [comment]
kind of duplicate of #78

**Comment by koddr** [comment]
Hi, @lmbek 

Can you please share output of the `gowebly doctor` command?

**Comment by lmbek** [comment]
Hello again,
I ran:

go run github.com/gowebly/gowebly/v2@latest doctor

✓ Your system information has been collected successfully!

│
│ Copy this information to paste into an issue ↘
│
│ Gowebly CLI: v2.6.0 (build with go1.22.1 on windows/amd64)
│
│ Go: 1.22.1 windows/amd64
│ Node.js version: 20.11.1 (npm 10.5.0)
│ Bun version: not installed
│
│ Is Air tool installed? false
│ Is Templ package installed? false


And here is the go.mod with the space character in the middle of the module name from the installation process

module github.com/lmbe k/myproject

go 1.22.0

require (
    github.com/a-h/templ latest
    
    github.com/angelofallars/htmx-go latest
    
    github.com/gowebly/helpers latest
)

**Comment by koddr** [comment]
@lmbek fixed in `v2.6.1`.
