### ISSUE TITLE
Improvement ideas: Improve onboarding experience

### ISSUE THREAD

**Issue by antran22** [gowebly/gowebly#81]
**Required check list:**

- [x] I didn't find in the repository's issues section a similar bug.
- [x] I understand, this is an Open Source and not-for-profit product.
- [x] This is not about a third-party project, framework, or technology.

**Is your feature request related to a problem? Please describe.**

Thanks for building this project. I would like to report several friction points during my process of creating my first project with Gowebly.
- If my current environment doesn't yet have the `templ` binary installed, the installation process will throw an error.
- The project creation form doesn't autofill the previous input when the previous execution is a failure. I have to re-input all my choices.
- The creation form should make clear that it will populate the files in the current working directory. 
- The output should have a README.md file describing how to run the application.

**Describe the solution you'd like:**

- We should detect the presence of the `templ` binary before execution, and optionally offer to install this library.
- should save & autofill the previous inputs in case the previous execution didn't finish.
- We can take inspiration from other project creation tools on the market, which allow users to choose the folder to populate the files (defaulting to the project's name). If the current directory is empty, offer to populate into the current directory instead.
- Populate a sample README.md file and output the final message to help the user to know the next step.

**Comment by koddr** [comment]
@antran22 thanks for the idea!

I will work around it soon.

**Comment by koddr** [comment]
Hi, @antran22 

In `v2.6.2` I added README.md a file with information about the generated project and some tips for developing, launching and deploying the application.

I hope this helps. If there are any comments or ideas to improve the README, please let me know!
