### ISSUE TITLE
bug: bun not found executable, but bun has no executable

### ISSUE THREAD

**Issue by sokoow** [gowebly/gowebly#82]
**Required check list:**

- [ x] I didn't find in the repository's issues section a similar bug.
- [ x] I understand, this is an Open Source and not-for-profit product.
- [ x] This is not about a third-party project, framework, or technology.

**My environment:**

```
# gowebly doctor

✓ Your system information has been collected successfully!
                                                          
│                                                          
│ Copy this information to paste into an issue ↘           
│                                                          
│ Gowebly CLI: v2.5.2 (build with go1.22.1 on linux/amd64) 
│                                                          
│ Go: 1.22.1 linux/amd64                                   
│ Node.js version: not installed (npm not installed)       
│ Bun version: not installed                               
│                                                          
│ Is Air tool installed? false                             
│ Is Templ package installed? true                         
│                                                          
                                                                    
✱ For more information go to the official docs: https://gowebly.org 
```
...

**Describe the bug:**
When selecting bun integration, gowebly tries to call bun executable, but according to https://github.com/uptrace/bun there's no cli tool for bun (at least not in that repo). Would you describe how you install bun cli?

**Expected behavior:**

no error when selecting bun integration

**Comment by iamdaiyuan** [comment]
You should install yarn。

**Comment by metafeather** [comment]
I think this is a misunderstanding between Bun the Go ORM from Uptrace and Bun the Javascript build tool: https://github.com/oven-sh/bun

**Comment by sokoow** [comment]
> I think this is a misunderstanding between Bun the Go ORM from Uptrace and Bun the Javascript build tool: https://github.com/oven-sh/bun

it is indeed
