### ISSUE TITLE
Echo template produces variable that shadows package name

### ISSUE THREAD

**Issue by pdf** [gowebly/gowebly#85]
**Required check list:**

- [x] I didn't find in the repository's issues section a similar bug.
- [x] I understand, this is an Open Source and not-for-profit product.
- [x] This is not about a third-party project, framework, or technology.

**My environment:**

│ Gowebly CLI: v2.5.2 (build with go1.22.4 on linux/amd64) 
│                                                          
│ Go: 1.22.4 linux/amd64                                   
│ Node.js version: 18.20.3 (npm 10.8.1)                    
│ Bun version: 1.1.13                                      
│                                                          
│ Is Air tool installed? true                              
│ Is Templ package installed? true                         

...

**Describe the bug:**

The Echo template declares the variable `echo`, which shadows the `echo` package. The declaration is here:

https://github.com/gowebly/gowebly/blob/a13360c239a011813759f1463022322e019f94a9/internal/attachments/templates/backend/echo/server.go.gotmpl#L47

This is poor form since it makes the `echo` package inaccessible in that scope, and will rightly trigger linters.

...

**Steps to reproduce the behavior:**

1. Create project using the Echo server template

**Expected behavior:**

The `echo` variable at the location linked above should be renamed. All the other templates (except fiber) name the equivalent var `router`.

**Comment by koddr** [comment]
@pdf fixed in `v2.6.0`.

**Comment by pdf** [comment]
LGTM
