### ISSUE TITLE
When going through the config naming the module doesn't let me go to next and adds white spaces to the input field

### ISSUE THREAD

**Issue by Silvallis** [gowebly/gowebly#86]
**Required check list:**

- [x] I didn't find in the repository's issues section a similar bug.
- [x] I understand, this is an Open Source and not-for-profit product.
- [x] This is not about a third-party project, framework, or technology.

**My environment:**

✓ Your system information has been collected successfully!

│
│ Copy this information to paste into an issue ↘
│
│ Gowebly CLI: v2.6.1 (build with go1.22.2 on windows/amd64) 
│
│ Go: 1.22.2 windows/amd64
│ Node.js version: 20.9.0 (npm 10.4.0)
│ Bun version: not installed
│
│ Is Air tool installed? false
│ Is Templ package installed? true
│

✱ For more information go to the official docs: https://gowebly.org 

...

**Describe the bug:**

When going through the configuration with the CLI command (go run github.com/gowebly/gowebly/v2@latest create) I get stuck on the step 'What's your Go module name in the go.mod file?'

When pressing enter on this step it just adds white spaces to the field. Even if not changing the name it still has 'focus' in the textfield.

I tried it with Windows Powershell, bash and cmd. All the same outcome.

...

**Steps to reproduce the behavior:**

1. Use any of mentioned command lines
2. Execute the command: go run github.com/gowebly/gowebly/v2@latest create
3. Go to the module name step and try to press enter

**Expected behavior:**

Pressing enter takes me to the next step instead of adding white spaces to the module name input

...

**Screenshots:**

![image](https://github.com/gowebly/gowebly/assets/33603070/5ee372e9-d110-45de-b87d-e892947f238d)

...

**Comment by koddr** [comment]
Hi, @Silvallis 

I did some CLI tests on a Windows 10 VM, but I didn't encounter this bug. Therefore, I'm not sure if it's the Gowebly CLI, maybe there's a problem in your system?

Can you please try to run the CLI via WSL?
