### ISSUE TITLE
Project creation on Windows is slow by 12 minutes !

### ISSUE THREAD

**Issue by RayyanNafees** [gowebly/gowebly#95]
**Required check list:**

- [x] I didn't find in the repository's issues section a similar bug.
- [x] I understand this is an Open Source and not-for-profit product.
- [x] This is not about a third-party project, framework, or technology.

**My environment:**
```powershell
 | Gowebly CLI: v2.6.6 (build with go1.22.5 on windows/amd64)
│
│ Go: 1.22.5 windows/amd64
│ Node.js version: 22.5.1 (npm 10.8.2)
│ Bun version: 1.1.21
│
│ Is Air tool installed? true
│ Is Templ package installed? true
```

---

**Describe the bug:**

# It took 12 minutes of just this

![image](https://github.com/user-attachments/assets/0069c476-39c2-400f-90de-b68b7cc89994)

---

**Steps to reproduce the behavior:**

1. `go install github.com/gowebly/gowebly/v2@latest`
2. `mkdir project`
3.  `cd project`
4.  `gowebly create`

**Expected behavior:**
Should've created a gowebly project and installed all required packages faster

**Additional Context**

![{AEDAAF05-AD0A-4CEB-8F66-6318A195F926}](https://github.com/user-attachments/assets/27ec91a4-df0a-4496-9a12-a90501f17662)

**Comment by koddr** [comment]
Hi, @RayyanNafees 

The CLI does the dependency installation, so it's not on the Gowebly or Windows side. 

Check your Internet connection, most likely it was very weak at the time of creation.
